# Generated by Django 3.2.5 on 2021-08-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Enter Your price'),
        ),
    ]
