# Generated by Django 3.2.5 on 2021-08-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_task_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='destinace',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='namber_percen',
            field=models.IntegerField(blank=True, null=True, verbose_name='Enter Your Nober percen'),
        ),
        migrations.AlterField(
            model_name='task',
            name='content',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
