# Generated by Django 3.2.5 on 2021-07-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_address', models.CharField(max_length=200, null=True)),
                ('A_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('A_Text', models.TextField(max_length=600)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
