# Generated by Django 3.2.5 on 2021-07-07 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='A_address',
            new_name='address',
        ),
    ]
