# Generated by Django 3.2.5 on 2021-07-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_excursions'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='name_activities',
            field=models.CharField(max_length=200, null=True, verbose_name='Enter Your name activite'),
        ),
        migrations.AddField(
            model_name='excursions',
            name='name_E',
            field=models.CharField(max_length=200, null=True, verbose_name='Enter Your name Excursions '),
        ),
        migrations.AlterField(
            model_name='activities',
            name='A_Text',
            field=models.TextField(max_length=600, verbose_name='Enter Your  commenter'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='A_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Enter Your name image'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='address',
            field=models.CharField(max_length=200, null=True, verbose_name='Enter Your city'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enter Your datae'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Enter Your price'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='Text_E',
            field=models.TextField(max_length=600, verbose_name='Enter Your commenter '),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='address_E',
            field=models.CharField(max_length=200, null=True, verbose_name='Enter Your city'),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='image_E',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Enter Your image '),
        ),
        migrations.AlterField(
            model_name='excursions',
            name='price_E',
            field=models.IntegerField(blank=True, null=True, verbose_name='Enter Your price '),
        ),
    ]
