# Generated by Django 3.2.5 on 2021-07-11 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_excursions_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcursionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/exurus')),
                ('excursions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.excursions')),
            ],
        ),
    ]
