# Generated by Django 3.2.5 on 2021-07-11 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_excursionsimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExcursionsImage',
            new_name='Images',
        ),
    ]
