# Generated by Django 3.2.5 on 2021-07-18 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_excursionsimage_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Traget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ctiy_start', models.CharField(blank=True, max_length=400, null=True)),
                ('Ctiy_and', models.CharField(blank=True, max_length=400, null=True)),
                ('Date_dipart', models.DateTimeField(blank=True, default=None, null=True)),
                ('Date_final', models.DateTimeField(blank=True, null=True)),
                ('Cart_status', models.CharField(blank=True, choices=[('Ecomi', '200'), ('Besnis', '200'), ('4X4', '200'), ('Minibost', '200'), ('autobost', '200')], max_length=200, null=True)),
                ('Adults_t', models.PositiveIntegerField()),
                ('Enfants_t', models.PositiveIntegerField()),
                ('Bebe_t', models.PositiveIntegerField()),
            ],
        ),
    ]
