# Generated by Django 3.2.5 on 2021-08-17 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_hoteladmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hotel',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.hoteladmin'),
            preserve_default=False,
        ),
    ]
