# Generated by Django 3.2.5 on 2021-08-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_auto_20210820_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user',
            new_name='costemer2',
        ),
    ]
